### ISSUE TITLE
Adapt to enable idempotent unsubscribe

### ISSUE THREAD

**Issue by kitten** [kitten/react-wonka#4]
With a React Refresh we can’t make assumptions about the cleanup effect anymore, so we may have to ensure that the unsubscribe can be called while the next render may then set up a new subscription.

**Comment by JoviDeCroock** [comment]
This should adapt to concurrent and react-refresh, right? https://github.com/kitten/react-wonka/pull/6 The `useMemo` will return again and the effects will rerun, no?

**Comment by kitten** [comment]
Fixed by #8
